pipeline {
    agent any
    stages {
    stage('maven install') {
      steps {
        withMaven(globalMavenSettingsConfig: maven: 'Maven3') {
      sh 'mvn clean install'
  }
      }
    }

  }

  
}
