pipeline {
    agent {
      label 'test5linux'
    }
    
    stages {
    stage('maven install') {
      steps {
        withMaven(maven: 'Maven3') {
        sh 'mvn clean install'
            def pom = readMavenPom file:'pom.xml'

                print pom.version
                env.version = pom.version
}
      }
    }

  }

  
}
